project:
  type: website

website:

  navbar:
    left: 
      - href: index.qmd
        text: Inicio
    right:
      - icon: github
        href: https://github.com/gpandradep
      - icon: twitter
        href: https://twitter.com/Gatorco_AP
      - icon: globe
        href: https://gpandradep.github.io/gpandradep/
format:
  html:
    theme: Lumen
    css: styles.css
    toc: true

editor: visual

