project:
  type: website
  output-dir: docs

website:
  page-footer:
    right: "Página construida con [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Gabriel Andrade-Ponce"
    background: "#D9E3E4"

  navbar:
    left: 
      - href: index.qmd
        text: Inicio
    right:
      - icon: github
        href: https://github.com/gpandradep
      - icon: twitter
        href: https://twitter.com/Gatorco_AP
      - icon: globe
        href: https://gpandradep.github.io/gpandradep/
format:
  html:
    theme: Lumen
    mainfont: "Palatino Linotype"
    fontsize: 1.5em
    css: styles.css
    toc: true

editor: visual

